name: Build, Create Release and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: npm run build --if-present
    
    - name: Test
      run: npm run test

    - name: Extract version from package.json
      id: package_version
      run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

    - name: Log the version
      run: echo "Building version ${{ env.VERSION }}"

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Extract version from package.json
      id: package_version
      run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
    
    - name: Create Tag and Release
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        if ! git rev-parse v${{ env.VERSION }} >/dev/null 2>&1; then
          git tag -a v${{ env.VERSION }} -m "Release v${{ env.VERSION }}"
          git push origin v${{ env.VERSION }}
          
          gh release create v${{ env.VERSION }} \
            --title "Release v${{ env.VERSION }}" \
            --notes "Release version ${{ env.VERSION }}"
        else
          echo "Tag v${{ env.VERSION }} already exists. Skipping tag and release creation."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    needs: release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Extract version from package.json
      id: package_version
      run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/angular-portfolio:latest
          ${{ secrets.DOCKER_USERNAME }}/angular-portfolio:v${{ env.VERSION }}
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/angular-portfolio:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/angular-portfolio:buildcache,mode=max